print('x:')
x = input()
print('*a:')
a = input()
print('/b:')
b = input()
print('+c:')
c = input()
print('-d:')
d = input()
answer = int(x) * int(a) / int(b) + int(c) - int(d)
print(str(x)+' * '+str(a)+' / '+str(b)+' + '+str(c)+' - '+ str(d)+' = '+str(answer)) 
